name: technical_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # advance toolTip
  just_the_tooltip: ^0.0.11+2
  # authentication
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  # manage image
  image_picker: ^0.8.4+11
  path_provider: ^2.0.9
  image_gallery_saver: ^1.7.1
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: 8156907eecfa812b181a5a729d790f6d399f311b
  # device permission
  permission_handler: ^9.2.0
  # fetch api
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/logo.png
    - assets/icons/google_icon.png